# Configuration file for ObsidianDestroyer
# Set LiquidMultiplier, Regen.Frequency or any ExplosionSource to -1 if you want to disable. Will also make blocks unbreakable. Set LiquidMultiplier to 1 if you want to bypass the function.
# DropChance is measured in percent. Default in Minecraft was 30 (%), but is based on the explosion strength now.
# BlockCracks interval is not recommended to be set over 15
# BedrockBlocking decides whether bedrock will make blocks in a direct path behind it take damage (false) or not (true)

BlastRadius: 2
LiquidMultiplier: 2
DurabilityChecker: '280'
VoidProtector: true
BedrockBlocking: true
DisabledWorlds:
- 'Insert world name here'
Drops:
  DropChance: 0
  DontDrop:
  - '7'
Blocks:
  '49': 2
  '116': 2
  '130': 2
Regen:
  Frequency: 10
  Amount: 1
BlockCracks:
  Enabled: true
  Interval: 5
ExplosionSources:
  PRIMED_TNT: 1
  CREEPER: 1
  GHAST: 1
  WITHER: 1
  MINECART_TNT: 1
